#!/usr/bin/env python

from pkg_resources import resource_filename, resource_listdir

if __name__ == '__main__':
    for fname in resource_listdir('rl', f'data/pomdp'):
        if fname.endswith('.pomdp'):
            print(fname.replace('.pomdp', ''))
